name: atlite
channels:
  - conda-forge
dependencies:
  - six
  - numpy
  - scipy
  - pandas>=0.22.0
  - xarray>=0.11.2
  - dask>=0.18.0
  - netcdf4
  - progressbar2
  - rasterio
  - geopandas
  - shapely

  # Recommended for pandas and xarray
  - bottleneck
  - numexpr

